"Yakui"
{
	"yakui"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"	"yakui"
		"xpos"		"r65"
		"ypos"		"r88"
		"zpos"		"100"
		"wide"		"64"
		"tall"		"64"
		"image"		"replay/thumbnails/yakui/yakui"
		"scaleImage"	"1"
		"visible"	"1"
		"enabled"	"1"
		"teambg_0"	"replay/thumbnails/yakui/yakui_think"
		"teambg_1"	"replay/thumbnails/yakui/yakui_think"
		"teambg_2"	"replay/thumbnails/yakui/yakui"
		"teambg_3"	"replay/thumbnails/yakui/yakui"
		"alpha"		"255"
	}
	"yakuidamage"
	{
		"ControlName"		"CTFImagePanel"
		"fieldName"		"yakuidamage"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"100"
		"wide"			"64"
		"tall"			"64"
		"image"			"replay/thumbnails/yakui/yakui_83"
		"visible"		"1"
		"alpha"			"0"
		"pin_to_sibling"	"yakui"
	}
	"charframe"
	{
		"ControlName"		"CTFImagePanel"
		"fieldName"		"charframe"
		"pin_to_sibling"	"yakui"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"99"
		"wide"			"64"
		"tall"			"64"
		"image"			"replay/thumbnails/yakui/frame"
		"scaleImage"		"1"
		"visible"		"1"
		"enabled"		"1"
	}
	"yakuitext"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"yakuitext"
		"pin_to_sibling"	"yakui"
		"xpos"			"31"
		"ypos"			"-2"
		"zpos"			"100"
		"wide"			"96"
		"tall"			"2.5"
		"labelText"		"YAKUI.EXE"
		"textAlignment"	"center"
		"font"			"FontStorePriceSmall"
		"fgcolor"		"TanLight"
		"visible"		"1"
		"enabled"		"1"
	}
	"yakuitextshadow"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"yakuitextshadow"
		"pin_to_sibling"	"yakuitext"
		"xpos"			"-1"
		"ypos"			"-1"
		"zpos"			"100"
		"wide"			"96"
		"tall"			"2.5"
		"labelText"		"YAKUI.EXE"
		"textAlignment"	"center"
		"font"			"FontStorePriceSmall"
		"fgcolor"		"Black"
		"visible"		"1"
		"enabled"		"1"
	}
}